//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyLibraryEntities : DbContext
    {
        public MyLibraryEntities()
            : base("name=MyLibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<BookType> BookType { get; set; }
        public virtual DbSet<BookTypeSec> BookTypeSec { get; set; }
        public virtual DbSet<Borrowinf> Borrowinf { get; set; }
        public virtual DbSet<BrowBook> BrowBook { get; set; }
        public virtual DbSet<Infringement> Infringement { get; set; }
        public virtual DbSet<LAdmin> LAdmin { get; set; }
        public virtual DbSet<Reader> Reader { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
    }
}
